val FORMATIONS = listOf(
    Formation(
        "3-1-4-2",
        listOf(
            Position.GK,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.LM,
            Position.CM,
            Position.CDM,
            Position.CM,
            Position.RM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "3-4-1-2",
        listOf(
            Position.GK,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.LM,
            Position.CM,
            Position.CAM,
            Position.CM,
            Position.RM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "3-4-2-1",
        listOf(
            Position.GK,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.LM,
            Position.CM,
            Position.CM,
            Position.RM,
            Position.CF,
            Position.ST,
            Position.CF
        )
    ),
    Formation(
        "3-4-3",
        listOf(
            Position.GK,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.LM,
            Position.CM,
            Position.CM,
            Position.RM,
            Position.LW,
            Position.ST,
            Position.RW
        )
    ),
    Formation(
        "3-5-2",
        listOf(
            Position.GK,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.LM,
            Position.CDM,
            Position.CAM,
            Position.CDM,
            Position.RM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "4-1-2-1-2",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CDM,
            Position.CAM,
            Position.RM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "4-1-2-1-2 (2)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CM,
            Position.CDM,
            Position.CAM,
            Position.CM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "4-1-3-2",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CDM,
            Position.CAM,
            Position.RM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "4-1-4-1",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CM,
            Position.CDM,
            Position.CM,
            Position.RM,
            Position.ST
        )
    ),
    Formation(
        "4-2-2-2",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CAM,
            Position.CDM,
            Position.CDM,
            Position.CAM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "4-2-3-1",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CAM,
            Position.CDM,
            Position.CAM,
            Position.CDM,
            Position.CAM,
            Position.ST
        )
    ),
    Formation(
        "4-2-3-1 (2)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CDM,
            Position.CAM,
            Position.CDM,
            Position.RM,
            Position.ST
        )
    ),
    Formation(
        "4-2-4",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CM,
            Position.CM,
            Position.LW,
            Position.ST,
            Position.ST,
            Position.RW
        )
    ),
    Formation(
        "4-3-1-2",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CM,
            Position.CM,
            Position.CAM,
            Position.CM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "4-3-2-1",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CM,
            Position.CM,
            Position.CM,
            Position.CF,
            Position.ST,
            Position.CF
        )
    ),
    Formation(
        "4-3-3",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CM,
            Position.CM,
            Position.CM,
            Position.LW,
            Position.ST,
            Position.RW
        )
    ),
    Formation(
        "4-3-3 (2)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CM,
            Position.CDM,
            Position.CM,
            Position.LW,
            Position.ST,
            Position.RW
        )
    ),
    Formation(
        "4-3-3 (3)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CDM,
            Position.CM,
            Position.CDM,
            Position.LW,
            Position.ST,
            Position.RW
        )
    ),
    Formation(
        "4-3-3 (4)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CM,
            Position.CAM,
            Position.CM,
            Position.LW,
            Position.ST,
            Position.RW
        )
    ),
    Formation(
        "4-3-3 (5)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.CM,
            Position.CDM,
            Position.CM,
            Position.LW,
            Position.CF,
            Position.RW
        )
    ),
    Formation(
        "4-4-1-1",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CM,
            Position.CM,
            Position.RM,
            Position.CF,
            Position.ST
        )
    ),
    Formation(
        "4-4-1-1 (2)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CM,
            Position.CAM,
            Position.CM,
            Position.RM,
            Position.ST
        )
    ),
    Formation(
        "4-4-2",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CM,
            Position.CM,
            Position.RM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "4-4-2 (2)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CDM,
            Position.CDM,
            Position.RM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "4-5-1",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CAM,
            Position.CM,
            Position.CAM,
            Position.RM,
            Position.ST
        )
    ),
    Formation(
        "4-5-1 (2)",
        listOf(
            Position.GK,
            Position.LB,
            Position.CB,
            Position.CB,
            Position.RB,
            Position.LM,
            Position.CM,
            Position.CM,
            Position.CM,
            Position.RM,
            Position.ST
        )
    ),
    Formation(
        "5-2-1-2",
        listOf(
            Position.GK,
            Position.LWB,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.RWB,
            Position.CM,
            Position.CAM,
            Position.CM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "5-2-2-1",
        listOf(
            Position.GK,
            Position.LWB,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.RWB,
            Position.CM,
            Position.CM,
            Position.LW,
            Position.ST,
            Position.RW
        )
    ),
    Formation(
        "5-1-2-2",
        listOf(
            Position.GK,
            Position.LWB,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.RWB,
            Position.CM,
            Position.CDM,
            Position.CM,
            Position.ST,
            Position.ST
        )
    ),
    Formation(
        "5-4-1",
        listOf(
            Position.GK,
            Position.LWB,
            Position.CB,
            Position.CB,
            Position.CB,
            Position.RWB,
            Position.LM,
            Position.CM,
            Position.CM,
            Position.RM,
            Position.ST
        )
    )
)
